concat
-

In [46]:
import pandas as pd

In [48]:
df1 = pd.DataFrame({
    'column_a' : [1, 2, 3, 4],
    'column_b': ['a', 'b', 'c', 'd'],
    'column_c': [True, True, False, True]
})
df1

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d      True

In [49]:
df2 = pd.DataFrame({
    'column_a' : [1, 2, 8, 5],
    'column_b': ['a', 'b', 't', 'f'],
    'column_c': [False, False, False, True]
})
df2

   column_a column_b  column_c
0         1        a     False
1         2        b     False
2         8        t     False
3         5        f      True

In [50]:
df = pd.concat([df1,df2],keys=['df1' , 'df2'] )
df

       column_a column_b  column_c
df1 0         1        a      True
    1         2        b      True
    2         3        c     False
    3         4        d      True
df2 0         1        a     False
    1         2        b     False
    2         8        t     False
    3         5        f      True

In [51]:
df = pd.concat([df1,df2] , ignore_index=True , axis=1)
df

   0  1      2  3  4      5
0  1  a   True  1  a  False
1  2  b   True  2  b  False
2  3  c  False  8  t  False
3  4  d   True  5  f   True

In [52]:
df = pd.concat([df1,df2] ,  axis=1)
df

   column_a column_b  column_c  column_a column_b  column_c
0         1        a      True         1        a     False
1         2        b      True         2        b     False
2         3        c     False         8        t     False
3         4        d      True         5        f      True

merge
-

In [53]:
df1 = pd.DataFrame({
    'column_a' : [1, 2, 3, 4],
    'column_b': ['a', 'b', 'c', 'd'],
    'column_c': [True, True, False, True]
})
df1

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d      True

In [54]:
df2 = pd.DataFrame({
    'column_a' : [1, 2, 8, 5],
    'column_b': ['a', 'b', 't', 'f'],
    'column_c': [False, False, False, True]
})
df2

   column_a column_b  column_c
0         1        a     False
1         2        b     False
2         8        t     False
3         5        f      True

In [55]:
dfm = pd.merge(df1,df2 , on='column_a')
dfm

   column_a column_b_x  column_c_x column_b_y  column_c_y
0         1          a        True          a       False
1         2          b        True          b       False

In [56]:
dfm = pd.merge(df1,df2 , on=['column_a','column_b'])
dfm

   column_a column_b  column_c_x  column_c_y
0         1        a        True       False
1         2        b        True       False

In [57]:
df1.rename(columns={'column_a':'new'} ,inplace=True)
df1

   new column_b  column_c
0    1        a      True
1    2        b      True
2    3        c     False
3    4        d      True

In [58]:
dfm = pd.merge(df1,df2 , left_on='new' , right_on='column_a')
dfm

   new column_b_x  column_c_x  column_a column_b_y  column_c_y
0    1          a        True         1          a       False
1    2          b        True         2          b       False