In [1]:
import pandas as pd
df = pd.read_csv('stdMarks.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      10 non-null     int64
 1   Math    10 non-null     int64
 2   Phy     10 non-null     int64
 3   Lang    10 non-null     int64
 4   Pass    10 non-null     object
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes

In [3]:
df.head(10)

   Id  Math  Phy  Lang Pass
0   1    30   40    80   No
1   2    60   65    45  Yes
2   3    35   40    70   No
3   4    70   75    50  Yes
4   5    80   80    40  Yes
5   6    90   95    70  Yes
6   7    85   85    60  Yes
7   8    40   30    80   No
8   9    30   40    50   No
9  10    35   40    55   No

In [7]:
df1 = df[['Math','Phy','Lang']]
ss =df1.corr(method='pearson')
ss

          Math       Phy      Lang
Math  1.000000  0.970892 -0.328193
Phy   0.970892  1.000000 -0.386725
Lang -0.328193 -0.386725  1.000000