In [2]:
import pandas as pd

df = pd.read_csv('results.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Mark    10 non-null     int64
 1   Grade   10 non-null     object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [7]:
df.head(11)

   Mark Grade
0    20     F
1    27     F
2    30     F
3    50     D
4    50     D
5    53     C
6    55     C
7    65     B
8    70     B
9    80     A

In [4]:
des = df['Mark'].describe()
des

count    10.000000
mean     50.000000
std      19.402176
min      20.000000
25%      35.000000
50%      51.500000
75%      62.500000
max      80.000000
Name: Mark, dtype: float64

In [8]:
des = df['Grade'].describe()
des

count     10
unique     5
top        F
freq       3
Name: Grade, dtype: object

In [9]:
import pandas as pd

df = pd.read_csv('Students_exams.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         1000 non-null   object
 1   math score     1000 non-null   int64
 2   reading score  1000 non-null   int64
 3   writing score  1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [10]:
dese = df.describe()
dese

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000