In [1]:
import pandas as pd

df = pd.read_csv('Students_exams.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         1000 non-null   object
 1   math score     1000 non-null   int64
 2   reading score  1000 non-null   int64
 3   writing score  1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [2]:
df.columns = [col.lower().replace(' ','_') for col in df.columns]
print(df.columns)

Index(['gender', 'math_score', 'reading_score', 'writing_score'], dtype='object')

In [3]:
statics = pd.DataFrame(columns=['statics' ,'math' , 'reading', 'writing'])
statics

Empty DataFrame
Columns: [statics, math, reading, writing]
Index: []

In [4]:
x = df['math_score'].count()
y = df['reading_score'].count()
c = df['writing_score'].count()

rows = {'statics' : 'count' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [5]:
x = df['math_score'].mean()
y = df['reading_score'].mean()
c = df['writing_score'].mean()

rows = {'statics' : 'mean' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [6]:
x = df['math_score'].min()
y = df['reading_score'].min()
c = df['writing_score'].min()

rows = {'statics' : 'min' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [7]:
x = df['math_score'].max()
y = df['reading_score'].max()
c = df['writing_score'].max()

rows = {'statics' : 'max' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [8]:
x = df['math_score'].median()
y = df['reading_score'].median()
c = df['writing_score'].median()

rows = {'statics' : 'median' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [9]:
x = df['math_score'].quantile(0.25)
y = df['reading_score'].quantile(0.25)
c = df['writing_score'].quantile(0.25)

rows = {'statics' : '25%' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [10]:
x = df['math_score'].std()
y = df['reading_score'].std()
c = df['writing_score'].std()

rows = {'statics' : 'std' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [11]:
x = df['math_score'].mode()[0]
y = df['reading_score'].mode()[0]
c = df['writing_score'].mode()[0]

rows = {'statics' : 'mode' , 'math' :x , 'reading' :y , 'writing':c}
d_rows= pd.DataFrame.from_records([rows])
statics = pd.concat([statics ,d_rows ] , ignore_index = True)

In [12]:
statics

  statics      math    reading    writing
0   count      1000       1000       1000
1    mean    66.089     69.169     68.054
2     min         0         17         10
3     max       100        100        100
4  median      66.0       70.0       69.0
5     25%      57.0       59.0      57.75
6     std  15.16308  14.600192  15.195657
7    mode        65         72         74